### ISSUE TITLE
Fix "method_lines" issue in src/Controllers/Reports/GenerateReportController.php

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/api-backend#10]
Method `__invoke` has 62 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/Reconmap/api-backend/src/Controllers/Reports/GenerateReportController.php#issue_5f762ce20cdd30000100008b

**Comment by thicolares** [comment]
@santiagolizardo I'm looking into it
