### ISSUE TITLE
Fix "method_lines" issue in src/ApiRouter.php

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/api-backend#16]
Method `mapRoutes` has 29 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/Reconmap/api-backend/src/ApiRouter.php#issue_5f76d1a37cf1e60001000089

**Comment by illusi0nary** [comment]
Hi,
i would like to give it a try. :-)

**Comment by santiagolizardo** [comment]
Fixed by #19
