### ISSUE TITLE
Fix "return_statements" issue in src/Services/Cvss.php

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/api-backend#20]
Avoid too many `return` statements within this method.

https://codeclimate.com/github/Reconmap/api-backend/src/Services/Cvss.php#issue_5f787993bf6317000100008a

**Comment by paresh27** [comment]
Can you assign it to me?

**Comment by santiagolizardo** [comment]
Sorry @paresh27 , the issue was fixed by somebody else. Thanks
