### ISSUE TITLE
API-backend 500 Internal Server error

### ISSUE THREAD

**Issue by garthoid** [Reconmap/api-backend#28]
**Describe the bug**
After following instruction in readme,  api-server is returning 500 Internal Server Error on wget.

**To Reproduce**
1. Git clone https://github.com/Reconmap/api-backend.git
2. cd api-backend
3. make
4. make tests
4. make start
5. wget localhost:8080 or wget localhost:8080/auditlog

```
user@host:/opt/github/api-backend# wget localhost:8080
--2021-02-03 15:30:22--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-02-03 15:30:22 ERROR 500: Internal Server Error.
```
or 

```
root@kanga:/opt/github/api-backend# wget localhost:8080/auditlog
--2021-02-03 15:33:25--  http://localhost:8080/auditlog
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-02-03 15:33:25 ERROR 500: Internal Server Error.
```

**Expected behavior**
A json response of some kind.

**Desktop (please complete the following information):**
 - OS: Unbuntu Server 18.04
 - Browser: N/A
 - Version: Git clone from today

Looking for information on how to generate logging information. No logging information.

**Comment by santiagolizardo** [comment]
Thanks for reporting this error @garthoid . The problem was probably related to a missing configuration file. The API requires a `config.json` but the file does not exist on a clean copy of the code.
To solve this stop the containers with `make stop`, copy `config-template.json` to `config.json` and start again with `make start`.
I'll make an improvement to the API to be more smart and return an error message if the file is missing as well as pre-populating a default config.json during make if one does not exist already.
Thanks!

**Comment by santiagolizardo** [comment]
I pushed some changes that should prevent this from happening again. Thanks for reporting this @garthoid !

```shell
santiago@home:~/reconmap/api$ wget http://localhost:8080/auditlog
--2021-02-05 22:23:48--  http://localhost:8080/auditlog
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2021-02-05 22:23:48 ERROR 503: Service Unavailable.

santiago@home:~/reconmap/api$ curl http://localhost:8080/auditlog
Missing API configuration file (config.json)

santiago@optiplex:~/workspace/reconmap/api$ tail -n 1 logs/application.log 
[2021-02-05T22:23:56.243765+00:00] http.ERROR: Missing API configuration file (config.json) [] []
```

**Comment by garthoid** [comment]
Thanks. I would also suggest adding that step to the documentation, however your update has helped.

```
**root@kali:/opt/github/web-client# curl http://localhost:8080
{"status_code":405,"reason_phrase":"Method Not Allowed"}root@kali:/opt/github/web-client# 
root@kali:/opt/github/web-client# 
root@kali:/opt/github/web-client# 
root@kali:/opt/github/web-client# wget http://localhost:8080
--2021-02-06 15:08:44--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 405 Method Not Allowed
2021-02-06 15:08:44 ERROR 405: Method Not Allowed.
**
```

The next problem is that the client cannot seem to connect via the frontend.  I have created the environment file as per the api-backend documentation and run the client with the docker command in the api-backend readme.

My result of login is "Network error when attempting to fetch resource". And "Network Error, please check connectivity with the API".

**Comment by santiagolizardo** [comment]
Hi @garthoid ; Not sure what the problem could be in this case. Is there anything on the logs folder? (eg logs/application.log)
If there are no clues there, try connecting to the API container with `make api-shell`, then inspecting the content of the nginx error log (eg `tail /var/log/nginx/error.log`)
Lastly, when you are in the browser attempting to login, what is the networks tab showing you? Is it attempting to connect to the right API URL? (http://localhost:8080) Are there any errors in the network or console? (CORS related, or otherwise)
Hope that helps you. Feel free to join us on Gitter if you prefer to chat https://gitter.im/reconmap/community

**Comment by garthoid** [comment]
In the api-backend directory: 
`root@kali:/opt/github/api-backend# ls -la logs
total 8
drwxr-xr-x  2 root root 4096 Feb  2 15:55 .
drwxr-xr-x 17 root root 4096 Feb  6 13:51 ..
root@kali:/opt/github/api-backend# 
`

And execing into the container with make shell

`root@kali:/opt/github/api-backend# make api-shell
root@ec3c983850ff:/var/www/webapp# ls -la
total 208
drwxr-xr-x  9 root root   4096 Feb  2 21:27 .
drwxr-xr-x  1 root root   4096 Feb  6 18:53 ..
-rw-r--r--  1 root root    956 Feb  6 18:51 composer.json
-rw-r--r--  1 root root 155766 Feb  6 18:51 composer.lock
-rw-r--r--  1 root root    412 Feb  2 20:47 config.json
drwxr-xr-x  5 root root   4096 Feb  1 19:22 data
drwxr-xr-x  2 root root   4096 Feb  2 20:55 logs
-rw-r--r--  1 root root    492 Feb  1 19:22 phpunit.xml.dist
drwxr-xr-x  3 root root   4096 Feb  6 18:51 public
drwxr-xr-x  3 root root   4096 Feb  6 18:51 resources
-rwxr-xr-x  1 root root     76 Feb  1 19:22 run-tests.sh
drwxr-xr-x 10 root root   4096 Feb  6 18:51 src
drwxr-xr-x  7 root root   4096 Feb  2 20:51 tests
drwxr-xr-x 27 root root   4096 Feb  6 18:53 vendor
root@ec3c983850ff:/var/www/webapp# cd logs
root@ec3c983850ff:/var/www/webapp/logs# ls -la
total 8
drwxr-xr-x 2 root root 4096 Feb  2 20:55 .
drwxr-xr-x 9 root root 4096 Feb  2 21:27 ..
root@ec3c983850ff:/var/www/webapp/logs# 
`

**Comment by garthoid** [comment]
FWIW:

`root@kali:/opt/github/api-backend# docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS        PORTS                               NAMES
636bd537c10f   quay.io/reconmap/web-client:master    "/docker-entrypoint.…"   21 hours ago   Up 21 hours   0.0.0.0:3001->80/tcp                reconmap-web-client
cb37e0107582   quay.io/reconmap/rest-api-db:latest   "docker-entrypoint.s…"   21 hours ago   Up 21 hours   0.0.0.0:3306->3306/tcp, 33060/tcp   rmap-mysql
ec3c983850ff   quay.io/reconmap/rest-api:latest      "/entrypoint /bin/sh…"   21 hours ago   Up 21 hours   0.0.0.0:8080->80/tcp                rmap-api
b46b2257b65f   quay.io/reconmap/ws-server:latest     "python3 /opt/reconm…"   4 days ago     Up 21 hours   0.0.0.0:8765->8765/tcp              rmap-wss
5ccf41272d4f   redis:6.0                             "docker-entrypoint.s…"   4 days ago     Up 21 hours   0.0.0.0:6379->6379/tcp              rmap-redis
`

**Comment by santiagolizardo** [comment]
Aha! I know what the problem might be....
Your config.json is 412 bytes long. That suggests to me you are missing some config sections such as cors and jwt.
Look at [this file](https://github.com/Reconmap/api-backend/blob/master/config-template.json) and make sure those sections are present.

**Comment by garthoid** [comment]
The JWT and cors sections are missing from mine. I have not integrations so I am not sure if this is mandatory to be there.

For the JWT section, this implies I need a JWT issued by the reconmap.org site?

**Comment by santiagolizardo** [comment]
The integrations section can be left empty. The JWT issuer and audience can take any value, it does not connect to external services to create the token, but for security reasons you need to set your own values to avoid tokens from other sites being used in yours or vice-versa. Hope that helps

**Comment by garthoid** [comment]
That was it. I have access to the backend from the client as per the api-backend readme. I will try the web-client repo next.

Recommend update the readme for what we discussed here.

Thanks.
