### ISSUE TITLE
Fix "method_lines" issue in src/Controllers/Users/CreateUserController.php

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/api-backend#3]
Method `__invoke` has 26 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/Reconmap/api-backend/src/Controllers/Users/CreateUserController.php#issue_5f5154e1b17329000100006a

**Comment by AbderrahimSoubaiElidrissi** [comment]
I will take this

**Comment by AbderrahimSoubaiElidrissi** [comment]
Just published PR: https://github.com/Reconmap/api-backend/pull/11
