### ISSUE TITLE
Fix "method_lines" issue in src/Controllers/Users/UsersLoginController.php

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/api-backend#9]
Method `__invoke` has 28 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/Reconmap/api-backend/src/Controllers/Users/UsersLoginController.php#issue_5f762ce20cdd30000100008a

**Comment by AbderrahimSoubaiElidrissi** [comment]
I will take this

**Comment by JordanaHarrison** [comment]
I'm interesting in taking this on.
